# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven # Tên của acttion buil

on: #xảy ra sự kiện để kích hoặc việc build
  push: 
    branches: [ master ]  # Khi code được push bên branch master
  pull_request:
    branches: [ master ]  # Khi có pull request ở branh master

jobs: # Những công việc sẽ được làm
  build:

    runs-on: ubuntu-latest   # Đây là môi trường, có thể chạy trên container này luôn hoặc docker

    steps:
    - uses: actions/checkout@v2 	# Lấy code của mình
    - name: Set up JDK 1.8     		# Tên của step là setup JDK 
      uses: actions/setup-java@v1   # Setup Java 
      with:
        java-version: 1.8           # Lựa chọn phiên bản 1.8 là JDK 8
    - name: Build with Maven 		# Tiếp theo là build
      run: mvn package  #Chạy lệnh build
    - name: Test with Maven  # Chạy test 
      run: mvn test && mvn package
    - name: Build Jar file
      run: mkdir staging && cp target/*.jar staging  # Đưa file jar vào artifact Github
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
  	
